-- Migration 001: Initial Schema for AeroCast

-- ==========================================
-- TABLE: flight_prices
-- ==========================================
CREATE TABLE public.flight_prices (
    id bigint generated by default as identity primary key,
    airline text not null,
    flight text,
    source_city text not null,
    departure_time text,
    stops text,
    arrival_time text,
    destination_city text not null,
    class text not null,
    duration numeric check (duration >= 0),
    days_left integer not null check (days_left >= 0),
    price integer not null check (price > 0),
    created_at timestamptz not null default now()
);

-- ==========================================
-- INDEXES for flight_prices
-- ==========================================
-- Main composite index for the common query pattern:
CREATE INDEX idx_flight_prices_search 
ON public.flight_prices (source_city, destination_city, class, days_left);

-- Additional indexes for potential filtering
CREATE INDEX idx_flight_prices_airline ON public.flight_prices (airline);
CREATE INDEX idx_flight_prices_price ON public.flight_prices (price);

-- ==========================================
-- TABLE: simulations
-- ==========================================
CREATE TABLE public.simulations (
    id uuid primary key default gen_random_uuid(),
    source_city text not null,
    destination_city text not null,
    class text not null,
    days_left integer not null check (days_left >= 0),
    days_tolerance integer not null default 0 check (days_tolerance >= 0),
    iteration_count integer not null check (iteration_count > 0),
    historical_sample_count integer,
    seed bigint,
    mean_price numeric,
    median_price numeric,
    p25 numeric,
    p75 numeric,
    minimum_price numeric,
    maximum_price numeric,
    std_deviation numeric,
    interval_95_low numeric,
    interval_95_high numeric,
    created_at timestamptz not null default now()
);

-- ==========================================
-- TABLE: simulation_buckets
-- ==========================================
CREATE TABLE public.simulation_buckets (
    id bigint generated by default as identity primary key,
    simulation_id uuid not null references public.simulations(id) on delete cascade,
    bucket_order integer not null,
    price_min numeric not null,
    price_max numeric not null,
    frequency integer not null check (frequency >= 0),
    probability numeric not null check (probability >= 0 and probability <= 1),
    cumulative_probability numeric not null check (cumulative_probability >= 0 and cumulative_probability <= 1),
    random_min integer check (random_min >= 0),
    random_max integer check (random_max <= 9999),
    created_at timestamptz default now()
);

-- ==========================================
-- TABLE: simulation_samples
-- ==========================================
CREATE TABLE public.simulation_samples (
    id bigint generated by default as identity primary key,
    simulation_id uuid not null references public.simulations(id) on delete cascade,
    iteration integer not null,
    random_number integer not null check (random_number >= 0 and random_number <= 9999),
    price_range_min numeric,
    price_range_max numeric,
    sampled_price numeric not null,
    created_at timestamptz default now()
);

-- ==========================================
-- TABLE: accuracy_tests
-- ==========================================
CREATE TABLE public.accuracy_tests (
    id uuid primary key default gen_random_uuid(),
    simulation_id uuid references public.simulations(id) on delete set null,
    train_ratio numeric not null check (train_ratio > 0 and train_ratio < 1),
    test_ratio numeric not null check (test_ratio > 0 and test_ratio < 1),
    train_samples integer,
    test_samples integer,
    mae numeric,
    mape numeric,
    rmse numeric,
    created_at timestamptz default now()
);

-- ==========================================
-- RLS (Row Level Security) POLICIES
-- ==========================================
-- Enable RLS on all tables
ALTER TABLE public.flight_prices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.simulations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.simulation_buckets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.simulation_samples ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accuracy_tests ENABLE ROW LEVEL SECURITY;

-- flight_prices: Allow anonymous read access
CREATE POLICY "Allow public read access to flight_prices" 
ON public.flight_prices 
FOR SELECT 
USING (true);

-- For simulations, buckets, samples, and accuracy_tests: 
-- Allow read for UI, but DO NOT allow unrestricted insert/update.
-- Write operations should eventually be handled server-side (using service_role)
-- or restricted to authenticated users when auth is added.
CREATE POLICY "Allow public read access to simulations" 
ON public.simulations FOR SELECT USING (true);

CREATE POLICY "Allow public read access to simulation_buckets" 
ON public.simulation_buckets FOR SELECT USING (true);

CREATE POLICY "Allow public read access to simulation_samples" 
ON public.simulation_samples FOR SELECT USING (true);

CREATE POLICY "Allow public read access to accuracy_tests" 
ON public.accuracy_tests FOR SELECT USING (true);

-- No INSERT/UPDATE/DELETE policies are created for anon/public to ensure security.
